### PR TITLE
Add support for CryptographyContext factories

### PR DESCRIPTION
**Pull request by dusk0r**
Currently there is no way to control the creation of (S/MIME / OpenPGP) CryptographyContexts. I propose optional factory methods.

### CODE REVIEW

**Comment by jstedfast** [comment]
Why not just subclass the context you want and register it's Type?

**Comment by jstedfast** [comment]
I much prefer the way it is now...

**Comment by dusk0r** [comment]
Because you can't use non-static external resources.

**Comment by jstedfast** [comment]
Can you give me an example of what you are trying to accomplish that can't be done by subclassing?

**Comment by jstedfast** [comment]
Keep in mind that your PR breaks existing users of MimeKit... :(

**Comment by jstedfast** [comment]
Actually, n/m, I looked at your PR again and it doesn't...

**Comment by dusk0r** [comment]
We have several ASP.NET webapps. On startup they fetch a private S/MIME Key to sign outgoing mails. I don't want to embed or store the certificate on the machine.

Right now my best solution is to fetch the key and store it into a static property. Then subclass the context and load the key from that property. But I don't like that solution.

**Comment by jstedfast** [comment]
Since it doesn't break API/ABI, I'm willing to merge this, but can you fix the code formatting/indenting to match the rest of the code? Thanks.

**Comment by jstedfast** [comment]
Awesome, thank you.

**Pull request merged**
