### PR TITLE
Async IO support

### PR DESCRIPTION
**Pull request by naeemkhedarun**
### Currently a work in progress, please do not merge.

These changes are around supporting the async implementation in PR https://github.com/jstedfast/MailKit/pull/231 and removing the need for the ICancellableStream code branches.

### CODE REVIEW

**Comment by jstedfast** [comment]
How does this impact performance? I have a bunch of sample messages in the jwz.mbox.txt file located in the UnitTests/TestData/mbox directory.

**Comment by naeemkhedarun** [comment]
Great thanks, I'll take a look at performance right after the tests pass.

**Comment by rtlayzell** [comment]
This is old, is it still a WIP?
Also could you follow the conventions for async (i.e. method names postfixed with `Async`)?

**Comment by naeemkhedarun** [comment]
@rtlayzell This is no longer WIP, I will close the PR.

**Pull request closed without merging**
