### PR TITLE
Spanify Filters

### PR DESCRIPTION
**Pull request by iamcarbon**
This PR spanifies the filters and encoding methods and removes a bunch of fixed statements.

While we are introducing new bounds checks by switching from pointers -> spans, we're eliminating pinning which can fragment the heap and degrade GC performance in a long running application. The fixed statement also has some overhead that we eliminate.

We can also use Unsafe.Write to eliminate bounds checks, but the gains are minor.

This also sets us up to eliminate more allocations in the calling methods for both inputs and outputs) in a subsequent PR.

This PR also:

- removes the unused System.Reflection.TypeExtensions dependency
- utilizes BinaryPrimitives to read integers

### CODE REVIEW

**Comment by iamcarbon** [comment]
@jstedfast ready for review.

**Comment by jstedfast** [comment]
I've cherry-picked the TypeExtensions, TnefReader BinaryPrimitives, DkimSimple/RelaxedFilter stuff.

I tried spanifying BestEncodingFilter a few days ago, but after benchmarking it, it was slower so hadn't committed it yet. That said, it may still be worth it. The same for the Base64/QuotedPrintable/UUEncode encoders/decoders. I don't think I benchmarked QEncoder/HexEncoder, but I want to do that to see how spanified versions of those compare.

Header.TryParse() I want to benchmark as well.

The DKIM filters I don't care about as much - their loops were simple/similar enough to some of the previous spanified blocks of code that I have benchmarked that I feel pretty good that they are either faster than the old pointer code or close enough that the difference is inconsequential.

As mostly a reminder to myself, the following commits are ones I still want to benchmark before merging:

* [Spanify Header.TryParse](https://github.com/jstedfast/MimeKit/pull/775/commits/a8585b2a4af0f6a9fc9bd213e1ae7956133d913e)
* [Spanify BestEncodingFilter](https://github.com/jstedfast/MimeKit/pull/775/commits/ecf6b3e2167d479edf652233e3afc607d0a23496)
* [Spanify QEncoder](https://github.com/jstedfast/MimeKit/pull/775/commits/9a7825c2852f73d36412e964569ae7c37c2dab4e)
* [Spanify HexEncoder](https://github.com/jstedfast/MimeKit/pull/775/commits/5cabfc76922e00a70c68611693138b2fc70aa392)
* [Simplify Encode loop](https://github.com/jstedfast/MimeKit/pull/775/commits/0608129e06b59e0f68d82af424885f61415ddf18)

**Comment by jstedfast** [comment]
Speaking of base64 encoding/decoding, I wanted to look into this: https://lemire.me/blog/2018/01/17/ridiculously-fast-base64-encoding-and-decoding/

**Comment by jstedfast** [comment]
BenchmarkDotNet=v0.13.1, OS=Windows 10.0.22000
Intel Core i7-9700 CPU 3.00GHz, 1 CPU, 8 logical and 8 physical cores
.NET SDK=6.0.200
  [Host]     : .NET 5.0.14 (5.0.1422.5710), X64 RyuJIT
  DefaultJob : .NET 5.0.14 (5.0.1422.5710), X64 RyuJIT


|        Method |       Mean |     Error |    StdDev |
|-------------- |-----------:|----------:|----------:|
|    HexEncoder | 704.566 us | 7.7828 us | 7.2800 us |
| NewHexEncoder | 819.866 us | 2.6923 us | 2.3867 us |
|      QEncoder |   1.000 us | 0.0164 us | 0.0145 us |
|   NewQEncoder |   1.033 us | 0.0090 us | 0.0075 us |

BenchmarkDotNet=v0.13.1, OS=Windows 10.0.22000
Intel Core i7-9700 CPU 3.00GHz, 1 CPU, 8 logical and 8 physical cores
.NET SDK=6.0.200
  [Host]     : .NET 6.0.2 (6.0.222.6406), X64 RyuJIT
  DefaultJob : .NET 6.0.2 (6.0.222.6406), X64 RyuJIT


|        Method |       Mean |      Error |     StdDev |     Median |
|-------------- |-----------:|-----------:|-----------:|-----------:|
|    HexEncoder | 661.162 us | 13.1233 us | 35.7028 us | 644.852 us |
| NewHexEncoder | 775.375 us | 10.0209 us |  9.3736 us | 773.011 us |
|      QEncoder |   1.118 us |  0.0130 us |  0.0115 us |   1.114 us |
|   NewQEncoder |   1.016 us |  0.0047 us |  0.0039 us |   1.016 us |

**Comment by iamcarbon** [comment]
@jstedfast Possible to run the BestEncodingFilter benchmark again with the latest Optimize BestEncodingFilter.Scan commit?

**Comment by jstedfast** [comment]
BenchmarkDotNet=v0.13.1, OS=Windows 10.0.22000
Intel Core i7-9700 CPU 3.00GHz, 1 CPU, 8 logical and 8 physical cores
.NET SDK=6.0.200
  [Host]     : .NET 5.0.14 (5.0.1422.5710), X64 RyuJIT
  DefaultJob : .NET 5.0.14 (5.0.1422.5710), X64 RyuJIT


|                     Method |        Mean |     Error |    StdDev |      Median |
|--------------------------- |------------:|----------:|----------:|------------:|
|    BestEncoding_LoremIpsum |    455.7 us |   8.18 us |  16.90 us |    448.0 us |
|      BestEncoding_GirlJpeg | 53,115.4 us | 283.85 us | 237.03 us | 53,024.0 us |
| NewBestEncoding_LoremIpsum |    617.8 us |   7.12 us |   6.66 us |    616.0 us |
|   NewBestEncoding_GirlJpeg | 61,425.6 us | 203.28 us | 190.15 us | 61,396.5 us |

BenchmarkDotNet=v0.13.1, OS=Windows 10.0.22000
Intel Core i7-9700 CPU 3.00GHz, 1 CPU, 8 logical and 8 physical cores
.NET SDK=6.0.200
  [Host]     : .NET 6.0.2 (6.0.222.6406), X64 RyuJIT
  DefaultJob : .NET 6.0.2 (6.0.222.6406), X64 RyuJIT


|                     Method |        Mean |       Error |      StdDev |      Median |
|--------------------------- |------------:|------------:|------------:|------------:|
|    BestEncoding_LoremIpsum |    550.4 us |     4.98 us |     4.66 us |    548.4 us |
|      BestEncoding_GirlJpeg | 53,520.3 us |   957.65 us |   848.93 us | 53,780.3 us |
| NewBestEncoding_LoremIpsum |    605.8 us |     8.31 us |     7.77 us |    605.9 us |
|   NewBestEncoding_GirlJpeg | 63,414.9 us | 1,359.43 us | 4,008.31 us | 61,473.6 us |

**Comment by iamcarbon** [comment]
Hah. Managed to do worse. :) -- thanks for checking! Will setup the benchmarks here and fuss with this a bit more later. Hard to beat this raw pointer code without using vectors!

**Comment by jstedfast** [comment]
I think we can close this. Most of the commits were merged and the bits that weren't were slower (sadly).

Great stuff overall :)

**Pull request closed without merging**
