### PR TITLE
Add a type converter for the InternetAddress type

### PR DESCRIPTION
**Pull request by 0xced**
This is useful to automatically convert strings to typed InternetAddress subclasses. For example, when using the `Microsoft.Extensions.Configuration` package.

### CODE REVIEW

**Comment by jstedfast** [comment]
I'll have to think about this...

**Comment by jstedfast** [comment]
Can the TypeConverter classes be internal or do they have to be public for this to work?

**Comment by 0xced** [comment]
I think they could be internal but we would lose the ability to specify another ParserOptions with the `Register` method.

Also, all the system type converter classes are public.

**Comment by jstedfast** [comment]
Can you show me an example of how you intend to use this?

I'm not very familiar with Microsoft.Extensions.Configuration and so I'm curious about how this would work.

**Comment by 0xced** [comment]
Will do next week when I'm back in front of a computer.

**Comment by jstedfast** [comment]
@0xced Just figured I'd poke you since you are likely back from vacation now.

**Comment by jstedfast** [comment]
I made some changes to this PR and manually merged it (couldn't push my changes to this PR branch).

**Pull request closed without merging**
