### PR TITLE
Reduce Allocations

### PR DESCRIPTION
**Pull request by iamcarbon**
- Introduces and uses a StringBuilder.Append(StringBuilder) polyfill to eliminate an allocation
- Introduces a custom splitter to eliminate a few array allocations (and suballocations)
- Refactors the header tokenizer to eliminate allocations (looks like we both jumped on this -- and I need to rebase)

### CODE REVIEW

**Comment by iamcarbon** [comment]
@jstedfast We should consider replacing Word with ReadOnlyMemory<char> (same structure / shape)

**Comment by iamcarbon** [comment]
I'll rebase this on-top of your work a bit later. Notable nits are the StringBuilder.Append(StringBuilder) polyfill and custom splitting logic. 

I've done a couple reviews of the library at this point -- the code is pretty darn optimized! Looks like were chomping at low level allocations at this point.  :)

**Comment by iamcarbon** [comment]
Next big possible optimization would be to use a ValueStringBuilder to eliminate all these StringBuilder allocations.

**Comment by jstedfast** [comment]
One thing we used in Visual Studio for Mac when I was on that team (I'm on VS Windows now) was a StringBuilder cache, which might be another possibility.

**Comment by jstedfast** [comment]
I like the Splitter stuff. Maybe call it StringSplitter?

This was all great stuff!

**Comment by jstedfast** [comment]
As you noted, I rewrote the Header TokenizeText method after being inspired by your changes. I had to get in on the Span action 😁

We can move the Break() method back out to be a static method like before if we can switch over to using a built-in struct/class. We don't have to use my Word struct.

I think I did that because I couldn't use IEnumerable<ReadOnlySpan<char>> as a return type.

**Pull request closed without merging**
